# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-31 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('login_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('mobile_number', models.CharField(blank=True, max_length=20)),
                ('add_phone_number', models.CharField(blank=True, max_length=20)),
                ('email_expiry_date', models.IntegerField(blank=True, null=True)),
                ('sms_expiry_date', models.IntegerField(blank=True, null=True)),
                ('magic_link_email', models.CharField(blank=True, max_length=100, null=True)),
                ('magic_link_sms', models.CharField(blank=True, max_length=100, null=True)),
                ('sms_resend_attempts', models.IntegerField(blank=True, default=0, null=True)),
                ('sms_resend_attempts_expiry_date', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'USER_DETAILS',
            },
        ),
    ]
