# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-01 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='email',
            field=models.CharField(blank=True, help_text='The Email Address of the applicant, using the following regex ^(07\\d{8,12}|447\\d{7,11}|00447\\d{7,11}|\\+447\\d{7,11})$', max_length=100),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='login_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique UUID4 Identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='mobile_number',
            field=models.CharField(blank=True, help_text="The Mobile Address of the applicant, using following regex ^([a-zA-Z0-9_\\-\\.']+)@([a-zA-Z0-9_\\-\\.]+)\\.([a-zA-Z]{2,5})$", max_length=20),
        ),
    ]
