# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-02 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='change_email',
            field=models.CharField(blank=True, help_text='The Updated Email Address of the applicant, using the following regex: ^(07\\d{8,12}|447\\d{7,11}|00447\\d{7,11}|\\+447\\d{7,11})$', max_length=100),
        ),
    ]
